# Generated by Django 6.1.1 on 2026-09-14 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id_bci', models.CharField(blank=True, db_index=True, max_length=64)),
                ('premio_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('certificado_apolice', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_offline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'processo offline',
                'verbose_name_plural': 'processos offline',
                'ordering': ('-criado_em',),
            },
        ),
    ]
